spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/internal?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=KST
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: <내 구글 계정>
    password: <내 구글 계정 패스워드>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: test
  code: test

springdoc:
  swagger-ui:
    path: /swagger-ui.html

cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: test
      secret-key: test
    bucket:
      image: sopt-makers-internal
naver-cloud-sms:
  accessKey: test
  secretKey: test
  senderPhone: test
  serviceId: test
oauth:
  registerPage: testUrl
  fb:
    redirect:
      auth: testUrl
      register: testUrl
    client:
      appId: test
      secret: test
  google:
    redirect:
      auth: testUrl
      register: testUrl
    client:
      id: test
      secret: test
  apple:
    auth:
      token:
        url: https://appleid.apple.com/auth/token
    revoke:
      url: https://appleid.apple.com/auth/revoke
    key:
      id: keyname
      url: https://appleid.apple.com/auth/keys
      path: static/AuthKey_keyname.p8
    aud: https://appleid.apple.com
    sub: bundle_id
    team:
      id: team_id
coffeechat:
  profile: testUrl
  logo: testUrl
  default: testUrl
slack:
  url: test