spring:
  profiles:
    active: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/internal?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=KST
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: <내 구글 계정>
    password: <내 구글 계정 패스워드>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: test
  code: test
  jwk:
    issuer: test

springdoc:
  swagger-ui:
    path: /swagger-ui.html

cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: test
      secret-key: test
    bucket:
      image: sopt-makers-internal
naver-cloud-sms:
  accessKey: test
  secretKey: test
  senderPhone: test
  serviceId: test
oauth:
  registerPage: testUrl
  dev-register-magic-number: test
  dev-register-qa-token: test
  fb:
    redirect:
      auth: testUrl
      register: testUrl
    client:
      appId: test
      secret: test
  google:
    redirect:
      auth: testUrl
      register: testUrl
    client:
      id: test
      secret: test
  apple:
    auth:
      token:
        url: https://appleid.apple.com/auth/token
    revoke:
      url: https://appleid.apple.com/auth/revoke
    key:
      id: keyname
      url: https://appleid.apple.com/auth/keys
      path: static/AuthKey_keyname.p8
    aud: https://appleid.apple.com
    sub: bundle_id
    team:
      id: team_id
    magic-number: test
    register-token: test
coffeechat:
  profile: testUrl
  logo: testUrl
  default: testUrl
slack:
  url: test
internal:
  official:
    url: test
    sopticle-key: test
  app:
    secret: test
  crew:
    url: test
dictionary:
  key: test

push-notification:
  server-url: test
  action: test
  x-api-key: test
  service: test
  
crew:
  server-url: test

member:
  profile:
    crew-default-img: test

gabia:
  sms-id: test
  api-key: test
  send-number: test

external:
  auth:
    url: test
    api-key: test
    service-name: test
    endpoints:
      jwk: /.well-known/jwks.json