AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Playground Backend DEV - Spring Boot JAR on AWS Lambda with SnapStart

Globals:
  Function:
    Timeout: 300
    MemorySize: 3072 # 메모리 최적화 (JAR 실행에 적절한 수준)
    Runtime: java17

Parameters:
  S3Bucket:
    Type: String
    Default: ""
    Description: S3 bucket containing the Lambda JAR
  S3Key:
    Type: String
    Default: ""
    Description: S3 key (path) to the Lambda JAR file
  Profile:
    Type: String
    Default: "lambda-dev"
    Description: Spring profile to use

Resources:
  PlaygroundApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "playground-api-dev-jar"
      CodeUri:
        Bucket: !Ref S3Bucket
        Key: !Ref S3Key
      Handler: org.sopt.makers.internal.LambdaHandler
      SnapStart:
        ApplyOn: PublishedVersions  # SnapStart 활성화
      AutoPublishAlias: live
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: !Ref Profile
          TZ: Asia/Seoul
          JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"

      Events:
        # Warmer 이벤트 (SnapStart와 함께 사용하면 효과적)
        Warmer:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Enabled: true
            Input: '{"warmer": true}'
        ApiProxy:
          Type: Api
          Properties:
            RestApiId: !Ref PlaygroundApi
            Path: /{proxy+}
            Method: ANY

  PlaygroundApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowMethods: "'GET,POST,PUT,PATCH,DELETE,OPTIONS'"
        AllowCredentials: false

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${PlaygroundApi}.execute-api.${AWS::Region}.amazonaws.com"

