AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Playground Backend DEV - Spring Boot on AWS Lambda Container

Globals:
  Function:
    Timeout: 300
    MemorySize: 3072 # 속도 개선을 위해 기본 스펙 높게 설정

Parameters:
  ImageUri:
    Type: String
    Description: ECR Image URI (need to be overridden)

Resources:
  PlaygroundApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "playground-api-dev"
      PackageType: Image
      ImageUri: !Ref ImageUri
      Architectures:
        - arm64
      AutoPublishAlias: live
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Warmer:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
            Enabled: true
        ApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref PlaygroundHttpApi
            Path: /
            Method: ANY
        ApiProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref PlaygroundHttpApi
            Path: /{proxy+}
            Method: ANY

  PlaygroundHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS

Outputs:
  ApiEndpoint:
    Description: "HTTP API Gateway endpoint URL"
    Value: !Sub "https://${PlaygroundHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
